CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nickname VARCHAR(80) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'USER' CHECK (role IN ('USER', 'ADMIN')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_alpha2 VARCHAR(2) NOT NULL UNIQUE,
    map_key VARCHAR(3) NOT NULL UNIQUE,
    name_ko VARCHAR(100) NOT NULL,
    name_en VARCHAR(120) NOT NULL,
    continent VARCHAR(60) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE domestic_regions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10) NOT NULL UNIQUE,
    map_key VARCHAR(20) NOT NULL UNIQUE,
    name_ko VARCHAR(80) NOT NULL,
    name_en VARCHAR(120) NOT NULL,
    region_type VARCHAR(30) NOT NULL DEFAULT 'SIDO',
    display_order INTEGER NOT NULL
);

CREATE TABLE bucket_places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(160) NOT NULL,
    travel_scope VARCHAR(20) NOT NULL CHECK (travel_scope IN ('DOMESTIC', 'INTERNATIONAL')),
    country_id BIGINT REFERENCES countries(id),
    domestic_region_id BIGINT REFERENCES domestic_regions(id),
    city_name VARCHAR(120),
    reason VARCHAR(1000),
    expected_budget NUMERIC(12, 2),
    desired_season VARCHAR(60),
    priority INTEGER NOT NULL DEFAULT 3 CHECK (priority BETWEEN 1 AND 5),
    status VARCHAR(20) NOT NULL DEFAULT 'WANT_TO_GO' CHECK (status IN ('WANT_TO_GO', 'PLANNING', 'BOOKED', 'VISITED', 'ON_HOLD')),
    reference_url VARCHAR(500),
    memo TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_bucket_places_scope_reference CHECK (
        (travel_scope = 'DOMESTIC' AND domestic_region_id IS NOT NULL AND country_id IS NULL)
        OR (travel_scope = 'INTERNATIONAL' AND country_id IS NOT NULL AND domestic_region_id IS NULL)
    )
);

CREATE TABLE trips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    bucket_place_id BIGINT REFERENCES bucket_places(id) ON DELETE SET NULL,
    title VARCHAR(160) NOT NULL,
    travel_scope VARCHAR(20) NOT NULL CHECK (travel_scope IN ('DOMESTIC', 'INTERNATIONAL')),
    country_id BIGINT REFERENCES countries(id),
    domestic_region_id BIGINT REFERENCES domestic_regions(id),
    city_name VARCHAR(120),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PLANNED' CHECK (status IN ('PLANNED', 'COMPLETED', 'CANCELLED')),
    travel_type VARCHAR(80),
    companion VARCHAR(120),
    summary TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_trips_date_range CHECK (end_date >= start_date),
    CONSTRAINT ck_trips_scope_reference CHECK (
        (travel_scope = 'DOMESTIC' AND domestic_region_id IS NOT NULL AND country_id IS NULL)
        OR (travel_scope = 'INTERNATIONAL' AND country_id IS NOT NULL AND domestic_region_id IS NULL)
    )
);

CREATE TABLE trip_days (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    day_no INTEGER NOT NULL CHECK (day_no > 0),
    travel_date DATE NOT NULL,
    title VARCHAR(160),
    memo TEXT,
    UNIQUE (trip_id, day_no),
    UNIQUE (trip_id, travel_date)
);

CREATE TABLE trip_timeline_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_day_id BIGINT NOT NULL REFERENCES trip_days(id) ON DELETE CASCADE,
    item_time TIME,
    title VARCHAR(160) NOT NULL,
    memo TEXT,
    place_name VARCHAR(160),
    address VARCHAR(300),
    latitude NUMERIC(9, 6),
    longitude NUMERIC(9, 6),
    cost NUMERIC(12, 2),
    category VARCHAR(20) NOT NULL CHECK (category IN ('PLACE', 'FOOD', 'ACTIVITY', 'MOVE', 'MEMO')),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_timeline_latitude CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_timeline_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);

CREATE TABLE trip_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    timeline_item_id BIGINT REFERENCES trip_timeline_items(id) ON DELETE CASCADE,
    owner_type VARCHAR(20) NOT NULL CHECK (owner_type IN ('TRIP_COVER', 'TIMELINE_ITEM')),
    storage_key VARCHAR(500) NOT NULL,
    file_url VARCHAR(500),
    original_file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL CHECK (file_size > 0),
    caption VARCHAR(500),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_trip_photos_owner CHECK (
        (owner_type = 'TRIP_COVER' AND timeline_item_id IS NULL)
        OR (owner_type = 'TIMELINE_ITEM' AND timeline_item_id IS NOT NULL)
    )
);

CREATE TABLE travel_checklists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    title VARCHAR(160) NOT NULL,
    progress_rate INTEGER NOT NULL DEFAULT 0 CHECK (progress_rate BETWEEN 0 AND 100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE travel_checklist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checklist_id BIGINT NOT NULL REFERENCES travel_checklists(id) ON DELETE CASCADE,
    category VARCHAR(80) NOT NULL,
    content VARCHAR(300) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'TODO' CHECK (status IN ('TODO', 'DONE')),
    sort_order INTEGER NOT NULL DEFAULT 0,
    due_date DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE travel_checklist_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_scope VARCHAR(20) NOT NULL CHECK (travel_scope IN ('DOMESTIC', 'INTERNATIONAL')),
    title VARCHAR(160) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (travel_scope, title)
);

CREATE TABLE travel_checklist_template_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL REFERENCES travel_checklist_templates(id) ON DELETE CASCADE,
    category VARCHAR(80) NOT NULL,
    content VARCHAR(300) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_trips_user_status_scope ON trips(user_id, status, travel_scope);
CREATE INDEX idx_trips_user_country_status ON trips(user_id, country_id, status);
CREATE INDEX idx_trips_user_domestic_region_status ON trips(user_id, domestic_region_id, status);
CREATE INDEX idx_trips_user_dates ON trips(user_id, start_date, end_date);
CREATE INDEX idx_bucket_places_user_status_scope ON bucket_places(user_id, status, travel_scope);
CREATE INDEX idx_bucket_places_user_country_status ON bucket_places(user_id, country_id, status);
CREATE INDEX idx_bucket_places_user_domestic_region_status ON bucket_places(user_id, domestic_region_id, status);
CREATE INDEX idx_trip_days_trip_date ON trip_days(trip_id, travel_date);
CREATE INDEX idx_timeline_items_day_time ON trip_timeline_items(trip_day_id, item_time);
CREATE INDEX idx_timeline_items_coordinates ON trip_timeline_items(latitude, longitude);
CREATE INDEX idx_trip_photos_trip ON trip_photos(trip_id);
CREATE INDEX idx_trip_photos_timeline_item ON trip_photos(timeline_item_id);
CREATE INDEX idx_checklists_trip ON travel_checklists(trip_id);
CREATE INDEX idx_checklist_items_checklist ON travel_checklist_items(checklist_id);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens(expires_at);
