INSERT INTO countries (code_alpha2, map_key, name_ko, name_en, continent, display_order) VALUES
('KR', '410', '대한민국', 'South Korea', 'Asia', 1),
('JP', '392', '일본', 'Japan', 'Asia', 2),
('US', '840', '미국', 'United States', 'North America', 3),
('FR', '250', '프랑스', 'France', 'Europe', 4),
('IT', '380', '이탈리아', 'Italy', 'Europe', 5),
('ES', '724', '스페인', 'Spain', 'Europe', 6),
('GB', '826', '영국', 'United Kingdom', 'Europe', 7),
('DE', '276', '독일', 'Germany', 'Europe', 8),
('TH', '764', '태국', 'Thailand', 'Asia', 9),
('VN', '704', '베트남', 'Vietnam', 'Asia', 10),
('SG', '702', '싱가포르', 'Singapore', 'Asia', 11),
('TW', '158', '대만', 'Taiwan', 'Asia', 12),
('CN', '156', '중국', 'China', 'Asia', 13),
('AU', '36', '호주', 'Australia', 'Oceania', 14),
('CA', '124', '캐나다', 'Canada', 'North America', 15),
('NZ', '554', '뉴질랜드', 'New Zealand', 'Oceania', 16),
('CH', '756', '스위스', 'Switzerland', 'Europe', 17),
('AT', '40', '오스트리아', 'Austria', 'Europe', 18),
('CZ', '203', '체코', 'Czechia', 'Europe', 19),
('TR', '792', '튀르키예', 'Turkey', 'Asia', 20);

INSERT INTO domestic_regions (code, map_key, name_ko, name_en, region_type, display_order) VALUES
('KR-11', 'KR-11', '서울특별시', 'Seoul', 'SIDO', 1),
('KR-26', 'KR-26', '부산광역시', 'Busan', 'SIDO', 2),
('KR-27', 'KR-27', '대구광역시', 'Daegu', 'SIDO', 3),
('KR-28', 'KR-28', '인천광역시', 'Incheon', 'SIDO', 4),
('KR-29', 'KR-29', '광주광역시', 'Gwangju', 'SIDO', 5),
('KR-30', 'KR-30', '대전광역시', 'Daejeon', 'SIDO', 6),
('KR-31', 'KR-31', '울산광역시', 'Ulsan', 'SIDO', 7),
('KR-36', 'KR-36', '세종특별자치시', 'Sejong', 'SIDO', 8),
('KR-41', 'KR-41', '경기도', 'Gyeonggi-do', 'SIDO', 9),
('KR-42', 'KR-42', '강원특별자치도', 'Gangwon State', 'SIDO', 10),
('KR-43', 'KR-43', '충청북도', 'Chungcheongbuk-do', 'SIDO', 11),
('KR-44', 'KR-44', '충청남도', 'Chungcheongnam-do', 'SIDO', 12),
('KR-45', 'KR-45', '전북특별자치도', 'Jeonbuk State', 'SIDO', 13),
('KR-46', 'KR-46', '전라남도', 'Jeollanam-do', 'SIDO', 14),
('KR-47', 'KR-47', '경상북도', 'Gyeongsangbuk-do', 'SIDO', 15),
('KR-48', 'KR-48', '경상남도', 'Gyeongsangnam-do', 'SIDO', 16),
('KR-49', 'KR-49', '제주특별자치도', 'Jeju', 'SIDO', 17);
