#!/usr/bin/env bash
# Travel Archive frontend verify-in-temp.sh
# Byte-copies current frontend/ into a private temp dir (skipping .env*, node_modules,
# .next, tsconfig.tsbuildinfo), then runs npm ci + lint + typecheck (+ full test/build
# with --full, or exact Vitest files passed via repeated --vitest <path>).
#
# User-local .env* is never copied or read. Source tsconfig.tsbuildinfo is recorded
# before/after to confirm we never modify it. Exit code is preserved on every step.
#
# Usage:
#   bash frontend/scripts/verify-in-temp.sh --evidence <abs-path> --full
#   bash frontend/scripts/verify-in-temp.sh --evidence <abs-path> \
#       --vitest src/lib/api/client.test.ts \
#       --vitest src/lib/auth/context.test.tsx

set -euo pipefail

EVIDENCE=""
FULL=0
VITESTS=()

usage() {
  cat <<EOF
Usage: $0 --evidence <abs-path> [--full | --vitest <frontend-relative-test-path>...]

Required:
  --evidence <path>   Absolute file path where command/exit/assertion log is appended.

Mode (exactly one):
  --full              Run npm ci + lint + typecheck + vitest run + next build.
  --vitest <path>     Run npm ci + lint + typecheck + vitest run on that exact file.
                      May be repeated for multiple files.

Options:
  -h, --help          Show this help.
EOF
  exit 64
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --evidence)
      EVIDENCE="${2:-}"; shift 2 ;;
    --full)
      FULL=1; shift ;;
    --vitest)
      [[ $# -ge 2 ]] || usage
      VITESTS+=("$2"); shift 2 ;;
    -h|--help) usage ;;
    *) echo "Unknown argument: $1" >&2; usage ;;
  esac
done

if [[ -z "$EVIDENCE" ]]; then echo "ERROR: --evidence is required" >&2; usage; fi
if [[ ! "$EVIDENCE" = /* ]]; then echo "ERROR: --evidence must be absolute" >&2; exit 64; fi
if [[ "$FULL" -eq 1 && ${#VITESTS[@]} -gt 0 ]]; then
  echo "ERROR: --full and --vitest are mutually exclusive" >&2; exit 64
fi
if [[ "$FULL" -eq 0 && ${#VITESTS[@]} -eq 0 ]]; then
  echo "ERROR: must specify --full or at least one --vitest" >&2; usage
fi

mkdir -p "$(dirname "$EVIDENCE")"
: > "$EVIDENCE"
log() { printf '%s\n' "$*" | tee -a "$EVIDENCE" >&2; }

SRC_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
log "== verify-in-temp.sh =="
log "src_dir=$SRC_DIR"
log "evidence=$EVIDENCE"
log "mode=$([ "$FULL" -eq 1 ] && echo full || echo "vitest:${#VITESTS[@]}")"

# Resolve frontend root (one above scripts/)
FRONTEND_ROOT="$(cd -- "$SRC_DIR/.." && pwd)"
log "frontend_root=$FRONTEND_ROOT"

# Baseline SHA of tsconfig.tsbuildinfo (must not change)
TSBUILDINFO="$FRONTEND_ROOT/tsconfig.tsbuildinfo"
if [[ -f "$TSBUILDINFO" ]]; then
  TSBI_BEFORE="$(shasum -a 256 "$TSBUILDINFO" | awk '{print $1}')"
  log "tsconfig.tsbuildinfo sha256(before)=$TSBI_BEFORE"
else
  TSBI_BEFORE=""
  log "tsconfig.tsbuildinfo absent before"
fi

# Make a private temp copy of frontend/, excluding user-local + generated bytes.
TMP_DIR="$(mktemp -d /private/tmp/ta-frontend-verify.XXXXXX)"
log "tmp_dir=$TMP_DIR"
trap 'rc=$?; log "cleanup tmp_dir=$TMP_DIR"; rm -rf "$TMP_DIR" || true; exit $rc' EXIT

rsync -a \
  --include='.env.sample' \
  --include='.env.example' \
  --exclude='.env*' \
  --exclude='node_modules' \
  --exclude='.next' \
  --exclude='tsconfig.tsbuildinfo' \
  "$FRONTEND_ROOT/" "$TMP_DIR/"

log "== copy complete =="
log "size=$(du -sh "$TMP_DIR" | awk '{print $1}')"

if [[ ! -f "$TMP_DIR/.env.sample" && ! -f "$TMP_DIR/.env.example" ]]; then
  log "ERROR: env sample/template missing in copy" >&2
  exit 2
fi

step() {
  local label="$1"; shift
  log "----- $label -----"
  log "\$ $*"
  if "$@" >>"$EVIDENCE" 2>&1; then
    log "[exit 0] $label"
    return 0
  else
    local rc=$?
    log "[exit $rc] $label FAILED"
    return $rc
  fi
}

OVERALL_RC=0
cd "$TMP_DIR"
step "npm ci" npm ci --no-audit --no-fund || OVERALL_RC=$?
step "npm run lint" npm run lint || OVERALL_RC=$?
step "npm run typecheck" npm run typecheck || OVERALL_RC=$?

if [[ "$FULL" -eq 1 ]]; then
  step "npm test" npm test || OVERALL_RC=$?
  step "npm run build" npm run build || OVERALL_RC=$?
else
  step "npm test (targeted)" npx vitest run -- "${VITESTS[@]}" || OVERALL_RC=$?
fi
log "overall_rc=$OVERALL_RC"

if [[ -n "$TSBI_BEFORE" ]]; then
  if [[ -f "$TSBUILDINFO" ]]; then
    TSBI_AFTER="$(shasum -a 256 "$TSBUILDINFO" | awk '{print $1}')"
    if [[ "$TSBI_AFTER" == "$TSBI_BEFORE" ]]; then
      log "tsconfig.tsbuildinfo sha256(after)=$TSBI_AFTER (unchanged)"
    else
      log "ERROR: tsconfig.tsbuildinfo changed: before=$TSBI_BEFORE after=$TSBI_AFTER" >&2
      exit 3
    fi
  else
    log "ERROR: tsconfig.tsbuildinfo disappeared" >&2
    exit 3
  fi
fi

log "== verify-in-temp.sh OK =="

exit "$OVERALL_RC"
