spring:
  application:
    name: travel-archive
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/travel_archive}
    username: ${DB_USERNAME:travel_archive}
    password: ${DB_PASSWORD:travel_archive}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: ${SERVER_PORT:8080}
