spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/travel_archive}
    username: ${DB_USERNAME:travel_archive}
    password: ${DB_PASSWORD:travel_archive}
  jpa:
    hibernate:
      ddl-auto: validate
